lidar:
  angle_increment: 0.0174533
  angle_max: 3.141592653589793
  angle_min: -3.141592653589793
  frame_id: laser_frame
  range_max: 10.0
  range_min: 0.12
  topic: /scan
occupancy_grid:
  free_value: 0
  map_height: 100
  map_width: 100
  occupied_value: 100
  origin:
    x: 0.0
    y: 0.0
    z: 0.0
  resolution: 0.1
  topic: /map
  unknown_value: -1
