<?xml version="1.0"?>
<robot name="spongebob" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Define robot constants -->
  <xacro:property name="wheel_radius" value="0.13"/>     <!-- radius of robot wheel-->
  <xacro:property name="wheels_base" value="0.50"/>       <!-- distance between center of left and right wheels-->

  <!-- Visual parameters -->
  <xacro:property name="caster_xoff" value="0.05"/>  <!-- x offset of caster from end of base plate -->
  <xacro:property name="wheel_width" value="0.08"/>
  <xacro:property name="base_width" value="0.40"/> <!-- Y axis -->
  <xacro:property name="base_length" value="0.52"/> <!-- X axis -->
  <xacro:property name="base_height" value="0.10"/> <!-- Z axis -->
  <xacro:property name="base_zoff" value="0.15"/>
  <xacro:property name="profile_width" value="0.03"/> 

  <material name="grey">
    <color rgba="0.75 0.75 0.75 1"/>
  </material>
  <material name="blue">
    <color rgba= "0 0 1 1"/>
  </material>
  <material name="black">
    <color rgba= "0 0 0 1"/>
  </material>
  <material name="red">
    <color rgba= "1 0 0 1"/>
  </material>

  <!-- Robot Base -->
  <link name="base_link">
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="${base_length/2} 0 ${base_zoff+base_height/2}" rpy="0 0 0"/>
    </collision>
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz="${base_length/2} 0 ${base_zoff+base_height/2}" rpy="0 0 0"/>
      <material name="grey"/>
    </visual>
  </link>

  <!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="${base_length/2} 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <link name="marking_base"/>

  <joint name="marking_base_joint" type="fixed">
    <parent link="marking_base"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <link name="marking_spot">
    <visual>
      <geometry>
        <cylinder radius="0.01" length="0.001"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="red"/>
    </visual>
  </link>

  <joint name="marking_joint" type="fixed">
    <parent link="marking_spot"/>
    <child link="marking_base"/>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <link name="caster">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius/2}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${wheel_radius/2}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="caster_joint" type="continuous">
    <parent link="base_link"/>
    <child link="caster"/>
    <origin xyz="${base_length-caster_xoff} 0 ${wheel_radius/2}" rpy="0 0 0"/>
    <axis xyz="0 1 1"/>
  </joint>

  <link name="bl_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="bl_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="bl_wheel"/>
    <origin xyz="0.0 ${wheels_base/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <link name="br_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="br_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="br_wheel"/>
    <origin xyz="0.0 ${-wheels_base/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

</robot>
